add full webproject
Alfredbis29/Math-Magicians2 pull request #8
Opened 2022-05-02 19:07 UTC by Alfredbis29

2022-05-02 20:03 UTC, Gambit142 requested changes
Hi @Alfredbis29 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Used `react-router-dom` ✔️ 
- Implemented full website according to project details ✔️ 

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-05-02 20:03 UTC, Gambit142 commented on src/Calculator.js
> +}
- [x] Kindly follow the design guideline for the Calculator Page. The words _**Let's do some Maths**_ are aligned to the left side while the operating calculator is aligned to the right side. Kindly implement this change. 👍 

### Your Design

![image](https://user-images.githubusercontent.com/77106962/166316721-0cc82a2a-56bb-4df1-bc2a-097481cb794e.png)

### Template Design

![image](https://user-images.githubusercontent.com/77106962/166316824-21b7d8fe-4a21-489d-a799-ae18627a70e3.png)

2022-05-02 20:19 UTC, Alfredbis29 commented on src/Calculator.js
> +}
Hello @Gambit142 thanks so much for the professional review
according to the styles the mention this: Add my own styles to improve the look and feel.

2022-05-02 20:29 UTC, Alfredbis29 commented on src/Calculator.js
> +}
I even use react-router , you can now check well

2022-05-02 20:31 UTC, Alfredbis29 commented on src/Calculator.js
> +}
Check-in app.js

2022-05-02 20:36 UTC, Gambit142 commented on src/Calculator.js
> +}
Hi @Alfredbis29,

The instruction says you should add your style but use the wireframe provided. So you can add your styles, but please follow the wireframes provided for each page. 👍

2022-05-03 10:58 UTC, Alfredbis29 commented on src/Calculator.js
> +}
Okay okay , thanks so for you professional review

2022-05-03 11:10 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @Alfredbis29,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-03 11:12 UTC, Alfredbis29 commented
Hello @TedLivist  Thanks so much for approval my project , i appreciate your professional review

2022-05-03 11:13 UTC, merged